// Campus Köthen App · AGPL-3.0-only
// Copyright © 2026 Erik Engler and Jona Sommer

import 'dart:convert';

import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';

import '../domain/grade.dart';
import '../domain/grade_cache_store.dart';
import 'grade_cache_codec.dart';

/// [GradeCacheStore] backed by an ENCRYPTED `hive_ce` box.
///
/// The grades are never written to a plain box or to SharedPreferences: the box
/// is opened with a random 256-bit AES key generated by a cryptographically
/// secure source ([HiveInterface.generateSecureKey]). Only that key lives in the
/// keychain/keystore; [clear] removes it together with the box contents, so the
/// leftover ciphertext becomes unreadable.
///
/// Reads are best effort (a corrupt or unavailable box degrades to "no cache",
/// never a crash). Only a successfully fetched report is ever written, so the
/// last good cache always survives a failed sync.
class EncryptedGradeCache implements GradeCacheStore {
  EncryptedGradeCache([FlutterSecureStorage? storage])
    : _storage =
          storage ??
          const FlutterSecureStorage(
            iOptions: IOSOptions(
              accessibility: KeychainAccessibility.first_unlock,
            ),
          );

  final FlutterSecureStorage _storage;

  static const String _boxName = 'campus_grades_cache_v1';
  static const String _keyName = 'grades.cache.key.v1';
  static const String _reportKey = 'report';
  static const String _lastSuccessKey = 'lastSuccess';
  static const String _lastAttemptKey = 'lastAttempt';

  Box<String>? _box;

  Future<Box<String>?> _openBox() async {
    if (_box != null && _box!.isOpen) return _box;
    try {
      await Hive.initFlutter();
      final List<int> key = await _cacheKey();
      _box = await Hive.openBox<String>(
        _boxName,
        encryptionCipher: HiveAesCipher(key),
      );
      return _box;
    } catch (_) {
      return null; // degrade to "no cache", never crash the screen
    }
  }

  Future<List<int>> _cacheKey() async {
    final String? existing = await _storage.read(key: _keyName);
    if (existing != null) {
      try {
        return base64Decode(existing);
      } catch (_) {
        // A corrupt stored key: start over with a fresh one.
      }
    }
    final List<int> key = Hive.generateSecureKey(); // 256-bit, CSPRNG
    await _storage.write(key: _keyName, value: base64Encode(key));
    return key;
  }

  @override
  Future<GradeReport?> readReport() async {
    final Box<String>? box = await _openBox();
    final String? raw = box?.get(_reportKey);
    if (raw == null) return null;
    try {
      return GradeCacheCodec.reportFrom(jsonDecode(raw));
    } catch (_) {
      return null;
    }
  }

  @override
  Future<void> writeReport(GradeReport report) async {
    final Box<String>? box = await _openBox();
    try {
      await box?.put(_reportKey, jsonEncode(GradeCacheCodec.report(report)));
    } catch (_) {}
  }

  @override
  Future<DateTime?> readLastSuccessfulSync() => _readDate(_lastSuccessKey);

  @override
  Future<void> writeLastSuccessfulSync(DateTime at) =>
      _writeDate(_lastSuccessKey, at);

  @override
  Future<DateTime?> readLastAttemptedSync() => _readDate(_lastAttemptKey);

  @override
  Future<void> writeLastAttemptedSync(DateTime at) =>
      _writeDate(_lastAttemptKey, at);

  Future<DateTime?> _readDate(String key) async {
    final Box<String>? box = await _openBox();
    final String? raw = box?.get(key);
    return raw == null ? null : DateTime.tryParse(raw);
  }

  Future<void> _writeDate(String key, DateTime at) async {
    final Box<String>? box = await _openBox();
    try {
      await box?.put(key, at.toUtc().toIso8601String());
    } catch (_) {}
  }

  @override
  Future<void> clear() async {
    try {
      final Box<String>? box = await _openBox();
      await box?.clear();
    } catch (_) {}
    try {
      await _storage.delete(key: _keyName);
    } catch (_) {}
  }
}
